### ISSUE TITLE
Pusher BroadCastException while testing

### ISSUE THREAD

**Issue by anabeto93** [beyondcode/laravel-websockets-demo#1]
Followed the steps as outlined. 
Hosted the application on localhost using vagrant at https://websocket-demo.app

Registered two new user accounts, one on chrome and the one on firefox.

However, everytime I enter a message and send, from the logs with fails.

Sample logs, below:

local.ERROR:  {"userId":1,"email":"a@b.com","exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0):

**Comment by ok200paul** [comment]
Hey @anabeto93 

I was getting this also, running the demo app under Valet. It looks like it's to do with SSL config. This fixed it for me:

1. Broadcasting config
`config/broadcasting.php`
Add the following to connections.pusher.options:
```
'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
```

2. JS config
`resources/js/bootstrap.js`
Make sure the window.Echo variable is set as follows:
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    encrypted: true,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
});
```

3. SSL config in websockets config
`config/websockets.php`
Make the 'ssl' config point to the CRT and KEY files. For example my one looks like this as I'm using valet - YMMV:
```
    /*
     * Define the optional SSL context for your WebSocket connections.
     * You can see all available options at: http://php.net/manual/en/context.ssl.php
     */
    'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => '/Users/MYNAME/.valet/Certificates/laravel-websockets-demo.app.crt',
        
        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => '/Users/MYNAME/.valet/Certificates/laravel-websockets-demo.app.key',
        
        /*
         * Passphrase with which your local_cert file was encoded.
         */
        'passphrase' => null
    ],
```

**Comment by anabeto93** [comment]
Hi @ok200paul thanks for your response. I tried using env variables for the SSL since the app will be hosted on a sandbox and eventually a production server, I guess that might've been the issue. 

I actually responded to a similar post [https://github.com/beyondcode/laravel-websockets/issues/29#issuecomment-445626171](url) as to how I got it working.

I will try your recommendation and give a feedback.
Thank you

**Comment by anabeto93** [comment]
I got it working.

**Comment by franzgithub25** [comment]
How do you solve this problem on pusher?

**Comment by J4si3k** [comment]
someone help to configure it? Default configuration throw `BroadcastException` @anabeto93 How did you solve this problem?

**Comment by bassbiteye45** [comment]
how did you solve it ?
