### ISSUE TITLE
Can laravel-websockets support video call?

### ISSUE THREAD

**Issue by soonleh** [beyondcode/laravel-websockets-demo#11]
Hi,
I have been trying out the demo and it works fine. So, I wonder if this package can support video calling function? If yes, then a few tips on how to implement will be appreciated...

**Comment by mkarnicki** [comment]
Websockets are not intended for video calls. You may want to look into WebRTC.

**Comment by ghost** [comment]
https://mupati.medium.com/adding-video-chat-to-your-laravel-app-9e333c8a01f3


this is using pusher , don't know if it is possible to implement here
