### ISSUE TITLE
Question, not issue- Does the demo function because I cannot get it to work

### ISSUE THREAD

**Issue by wayneburlingame** [beyondcode/laravel-websockets-demo#13]
Question, not issue- Does the demo function because I cannot get it to work
Hello, I just was curious about this project and wanted to run demo but am I confused about what I  should see?
I think I get through all the steps for setup, but then run serve command and it just sits there.

I am just hoping you can help me understand if I am setting up demo properly, and if something is viewable vie apache web server on a specific port and see demo or if this is only a service type repo and I will not see anything, and that is expected?

**Comment by redalpha01** [comment]
I ran on a wamp and everything went fine (locally).
Not to be demeaning but : 
1. did you manage to migrate properly 
2. Did you set up a web server (I'm using wamp's vhost) 
3. If you're not working locally, is your port 6001. 

etc.

**Comment by sjorskoot** [comment]
It is a chat application. If you're familiar with Laravel, you probably know `php artisan serve`. You need to use that in a seperate console from the one in which you run `php artisan websockets:serve`.  This gives you a URL like `http://localhost:8000/` which you can enter in the browser. Using two private browser tabs, you can create two users that can chat with each other. I think it's pretty awesome :)

**Comment by blakeyman** [comment]
Nope - it doesn't work...
