### ISSUE TITLE
artisan on line 18

### ISSUE THREAD

**Issue by mohits4** [beyondcode/laravel-websockets-demo#16]
D:\xampp7.3\htdocs\laravel-websockets-demo>php artisan migrate
PHP Warning:  require(D:\xampp7.3\htdocs\laravel-websockets-demo/vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp7.3\htdocs\laravel-websockets-demo\artisan on line 18

Warning: require(D:\xampp7.3\htdocs\laravel-websockets-demo/vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp7.3\htdocs\laravel-websockets-demo\artisan on line 18
PHP Fatal error:  require(): Failed opening required 'D:\xampp7.3\htdocs\laravel-websockets-demo/vendor/autoload.php' (include_path='D:\xampp7.3\php\PEAR') in D:\xampp7.3\htdocs\laravel-websockets-demo\artisan on line 18

Fatal error: require(): Failed opening required 'D:\xampp7.3\htdocs\laravel-websockets-demo/vendor/autoload.php' (include_path='D:\xampp7.3\php\PEAR') in D:\xampp7.3\htdocs\laravel-websockets-demo\artisan on line 18

**Comment by infureal** [comment]
Because you need to run `composer install`
