### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by jamesbhatta** [beyondcode/laravel-websockets-demo#17]
I an getting following error while running ``composer install``

```bash
In PackageManifest.php line 122:

  Undefined index: name
```

**Comment by dorkyboi** [comment]
@mpociot, @freekmurze, the issue is still standing. What can we do about it?

**Comment by damieneskimo** [comment]
likely to a composer version issue. If you try to downgrade composer to version 1, it should work fine.

**Comment by LucasMali** [comment]
`composer self-update --1`

Or you can modify the core files (not recommended for production). https://stackoverflow.com/questions/61177995/laravel-packagemanifest-php-undefined-index-name

**Comment by blakeyman** [comment]
This issue IS beacsue you have to use Composer V1 to install
Alternative option: use a composer.phar (version 1) if you don't want to downgrade your local machine
https://getcomposer.org/download/1.10.20/composer.phar

**Comment by davidtowoju** [comment]
To use @mhyeganeh Laravel v9 pull,

```
git clone https://github.com/beyondcode/laravel-websockets-demo.git
cd laravel-websockets-demo
git fetch origin pull/23/head:pull_request_23
git checkout pull_request_23
composer install
cp .env.example .env
php artisan migrate
php artisan key:generate
php artisan websockets:serve
```

This should work fine without the need to downgrade composer
