### ISSUE TITLE
Unable to get demo working...

### ISSUE THREAD

**Issue by scramatte** [beyondcode/laravel-websockets-demo#2]
Hi

Following documentation I've setup  server to listen 127.0.0.1:6001 and proxy it with nginx to be able to use SSL.   I've setup supervisord too.

Unfortunatly I'm unable to get demo working.  Neither Chat APP or Websockets Dashboard are working. I don't know how to change path to the wss  in the fronted.  

My browser returns me  "Unable to connect to websocket ..."

NOTE: I'm running Nginx + PHP 7.3  over Debian Jessie.

Regards

**Comment by anabeto93** [comment]
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    //wssPort: 6001,
    disableStats: true,
    encrypted: true
});

Edit your *bootstrap.js* file found in resources/assets/js. You will have to install your node_modules packages in order to recompile.
