### ISSUE TITLE
Not getting install with latest Laravel version

### ISSUE THREAD

**Issue by mukeshtilokani** [beyondcode/laravel-websockets-demo#21]
I am getting error like attachment while installing this package.

![websocket](https://user-images.githubusercontent.com/33526920/140390138-22f35ed3-3cd8-4031-8ce6-a88c536d185e.png)

**Comment by claudesimo1990** [comment]
you can delete your composer.lock.json and run composer require ...

**Comment by internetbug256** [comment]
Definitely this demo doesn't work with latest laravel (8.x).
Since this seems to be a so popular package, maybe authors should update this so we, newbies, have less work in the learning curve...
Thanks.

**Comment by mukeshtilokani** [comment]
> you can delete your composer.lock.json and run composer require ...

Ok, I will try it.

**Comment by erikn69** [comment]
Example updated #22
