### ISSUE TITLE
user is typing for ever

### ISSUE THREAD

**Issue by george-kar** [beyondcode/laravel-websockets-demo#3]
Although the message "user typing" appears when user is typing, it doesn't disappear when the user stops typing. is it a bug or not implemented?

**Comment by redalpha01** [comment]
If you look at the js, the code is implemented so that "typing" starts when any char is entered and finishes only when a messages is sent.
Obviously you can change that behaviour.

**Comment by sjorskoot** [comment]
I agree that this is odd default behaviour. I think adding this feature will demonstrate even better the real-timeness that is possible.
